name: content-contribution
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,7 * * *'
jobs:
  contributions:
    if: (github.repository == 'Adventech/sabbath-school-lessons' && github.ref_name == 'stage')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: npm install
      - run: node runners/content-contribution.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}